### ISSUE TITLE
Ability to maybe link multiple binscreen(s) together to a OC program, that you can control what text is put on it/the pastebin url remotely?

### ISSUE THREAD

**Issue by keanucz** [osmarks/binscreen#1]
Maybe a neat future feature enhancement.
It **would** be nice.

**Comment by osmarks** [comment]
This is two issues, please keep them separated.

So, you want remote control of the binscreens? Via what? And you want to run two at once? I guess that the second one might be feasible, but I'm not really sure if term can do that.

**Comment by keanucz** [comment]
Woah.

**Comment by osmarks** [comment]
?
